version: '3'

services:
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: pos3mlet
      ME_CONFIG_BASICAUTH_PASSWORD: pos3mlet
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    # links:
    #   - mongo
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    container_name: mongo
    #user: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: ["bash", "-c", "chown mongodb:mongodb /data && mongod"]
    ports:
      - "27017:27017"
    volumes:
      - ./database/MongoDB:/data/db
    networks:
      - mongo-compose-network
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

networks: 
    mongo-compose-network:
      driver: bridge